### PR TITLE
Updating Primitive types to Optional fields

### PR DESCRIPTION
**Pull request by ANISH-GOTTAPU**
To address https://github.com/open-traffic-generator/openapiart/issues/288

### CODE REVIEW

**Review by ajbalogh — COMMENTED** [review]
If the field is marked as optional it no longer adheres to the model. Anyone implementing the .proto independently of the non-conforming go wrapper will assume that all fields are optional.

**Comment by ajbalogh** [comment]
I disagree with the proposed change.
Required fields should remain as required as there is a discrepancy between openapi.yaml and the generated .proto and documenting a field as required but marking it as optional only confuses those looking at the .proto file.

The underlying generated fluent wrapper should account for required fields being set/not set, using some internal approach of marking required fields as dirty/not set/touched etc.

**Comment by ANISH-GOTTAPU** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by ashutshkumr** [comment]
Fixed by https://github.com/open-traffic-generator/openapiart/pull/412

**Pull request closed without merging**
