### PR TITLE
Addressing #246 and small change in Iters wrapper list

### PR DESCRIPTION
**Pull request by Rangababu-R**
#246 and #247
Change in Iters wrapper list

Need to add Tests for Items

### CODE REVIEW

**Review by ajbalogh — APPROVED** [review]

**Review by ashutshkumr — CHANGES_REQUESTED** [review]
We shouldn't have to check for this. 

```go
	if value == `""` {
		value = ""
	}
```

What I mean is, we should just check for empty string and change it to `{}` wherever relevant. We shouldn’t be checking for string containing two double-quotes.

**Comment by Rangababu-R** [comment]
> We shouldn't have to check for this.
> 
> ```go
> 	if value == `""` {
> 		value = ""
> 	}
> ```
> 
> What I mean is, we should just check for empty string and change it to `{}` wherever relevant. We shouldn’t be checking for string containing two double-quotes.

removed

**Comment by Rangababu-R** [comment]
mistakenly closed

**Comment by ashutshkumr** [comment]
Although I'm pretty much convinced that this change is in a correct direction, there are few things we should look into and implement if it makes sense. Please note, more evaluation may be needed to ensure that suggestions below will actually help:
- First something cosmetic. What's wrong with just using actual member name for wrapper/holder attributes (instead of suffixing them with `Holder`) ? The reason I'm mentioning this is because we now have so many names that compilation is now getting slower. Having shorter names may help.
- Every time we do `FromJson`, we should set all wrapper attributes to `nil`. Doing this ensures that underlying proto attribute is changed only from three methods:
  - `SetAttr()`
  - `Attr()` (upon calling `NewObj()` or `FromJson`, or in isolation)

  Thus hopefully this will simplify the logic of `Attr()`
  ```go
	func (obj *prefixConfig) RequiredObject() EObject {
		if obj.obj.RequiredObject == nil {
			obj.obj.RequiredObject = NewEObject().Msg()
		}

		if obj.requiredObjectHolder == nil {
			obj.requiredObjectHolder = &eObject{obj: obj.obj.RequiredObject}
		}

		return obj.requiredObjectHolder
	}
  ```

- Explore pointer-to-pointer for wrapper attributes. It requires more experiments, but will greatly reduce the work required to maintain wrapper objs. e.g.

```go
type eObject struct {
	obj **sanity.EObject
}

type prefixConfig struct {
	obj                   *sanity.PrefixConfig
	requiredObjectHolder  EObject
}

func NewPrefixConfig() PrefixConfig {
	obj := prefixConfig{obj: &sanity.PrefixConfig{}}
        obj.requiredObjectHolder = &eObject{obj: &obj.obj.RequiredObject}
	obj.setDefault()
	return &obj
}

func (obj *prefixConfig) RequiredObject() EObject {
	if obj.obj.RequiredObject == nil {
		obj.obj.RequiredObject = NewEObject().Msg()
	}

	return obj.requiredObjectHolder
}
```

- Need to understand changes related to iterators. The main reason why we got to this PR is because we were trying to fix an issue with iterators which in turn was a result of introducing wrappers for internal slices (to avoid extra work). But now that we see, we still end up doing similar amount of work. What's important is to check if the suggestions before this point make sense and can be implemented. If so, will it help reducing the work we do for iterators ?

**Review by ashutshkumr — APPROVED** [review]

**Pull request merged**
