### PR TITLE
Issue 240 and validate_method restructure

### PR DESCRIPTION
**Pull request by Rangababu-R**
Addressed #240 and https://github.com/open-traffic-generator/openapiart/issues/239
restructured the def _write_validate_method in an order of field type

### CODE REVIEW

**Review by ashutshkumr — CHANGES_REQUESTED** [review]
Why aren't we setting defaults when calling `Validate()` ?


```go
func (obj *prefixConfig) Validate() error {
	obj.validateObj(false)
	return validationResult()
}
```

**Comment by ashutshkumr** [comment]
What's the motivation behind calling it `validateText` ? Shouldn't we just call `Validate()` ?

```go
err := obj.validateFromText()
```

**Comment by ashutshkumr** [comment]
Following error message needs a bit of modifcation:

any int32 -> actual max value

```
PrefixConfig.Space_1 shall be in the range of [0, any int32] but Got
```

**Comment by ashutshkumr** [comment]
Why are we checking whether `space_1` is less than 0 ? From spec, it seems as if it has no constraints:

```yaml
        space_1:
          type: integer
```

**Comment by Rangababu-R** [comment]
> 
> 
> What's the motivation behind calling it `validateText` ? Shouldn't we just call `Validate()` ?
> 
> ```go
> err := obj.validateFromText()
> ```

After the unmarshal of a JSON, YAML or PBText we need to set the defaults as well. in the earlier approach we had used Validate with a defaults bool argument which would have control to set defaults or not, as we decided to remove the argument now separating the validate Api for FromJson(will be internal) and Validate for external.

**Comment by ashutshkumr** [comment]
@Rangababu-R I'll hold the merge for now because I noticed the error messages were modified as well.

Although new error messages are better, this is breaking negative tests for controller (since they rely on older error message).

Let's use this PR to conclude on our final error messaging.

**Review by ashutshkumr — APPROVED** [review]

**Pull request merged**
