### PR TITLE
Exposing Grpc Connect and Client

### PR DESCRIPTION
**Pull request by Rangababu-R**
Addresses the below issue
https://github.com/open-traffic-generator/snappi/issues/134

### CODE REVIEW

**Review by rudranil-das — APPROVED** [review]

**Comment by Rangababu-R** [comment]
@ajbalogh Could you please provide your inputs on exposing grpcClient and Connect calls. As this will serve Athena-G implementation at controller

**Comment by ajbalogh** [comment]
I still don't understand why this needs to be exposed - Please provide a fully coded use case.

**Comment by Rangababu-R** [comment]
@rudranil-das @ashutshkumr Could you please provide the insights of implementation to Andy.

**Review by ajbalogh — COMMENTED** [review]
This appears to be redundant as there already is a .SetConfig exposed.

**Comment by ashutshkumr** [comment]
I agree, it's not clear to me why we need this.

**Comment by ashutshkumr** [comment]
Checked with @rudranil-das further on the usecase. Existing functionality (`NewGrpcTransport()`) should suffice.

**Pull request closed without merging**
